### ISSUE TITLE
form_example

### ISSUE THREAD

**Issue by cwlfw** [romm/formz#4]
Hi Romain,
thanks for formz and formz_example. I installed the extensions which worked fine. But I could not find the TypoScript static content form Form example - Configuration (formz_example) as described here
https://github.com/romm/formz_example
Since I am not a developer, I have no idea how I can run the Example.
Maybe you have any advise.
Best wishes,
Franz

**Comment by romm** [comment]
Hi @cwlfw, thanks for your feedback!

How did you install these extensions? With Composer or the "normal" way?

Are you sure you installed correctly the two extension **formz** and **formz_example** in the **Extension Manager**?

Did you succeed to add the other TypoScipt static contents from **formz**?

One more thing concerning this issue, as this seems to be related only to **formz_example**, this issue should have been posted here instead: https://github.com/romm/formz_example/issues ; No big deal though. :)

**Comment by cwlfw** [comment]
Hi Romain,

thanks for your informations. I checked the installation of 
*formz_example *and installed it again with the Extension Manager.
Now the ypoScript static content form Form example - Configuration 
(formz_example)  was available.

But now I just get an empty page. You can see it here
https://www.tp764.cwl24.com/index.php?id=129

Many thanks for any advise.
Franz

Am 06.10.2016 um 11:35 schrieb Romain Canon:

**Comment by romm** [comment]
Did you insert any record on this page? Can you try adding a simple text element (in the **Page** module)?

If you did not already, you also have to insert the plugin provided by **formz_example**.

**Comment by cwlfw** [comment]
Hi,

there is now also a simple Text-element on this Page (made with the Page 
module).

In the Ext-Manager debug mode is on (in formz) but still an empty page.

https://www.tp764.cwl24.com/index.php?id=129

Franz

Am 06.10.2016 um 14:07 schrieb Romain Canon:

**Comment by romm** [comment]
Can you tell me the TYPO3 version of this instance? Formz doesn't support TYPO3 v8.x yet (I will soon begin the work to make it available).

Having a blank page means you did not activate TYPO3 debug mode. Can you please go in the install tool, and put the environment mode to **Development**? You should then have some error message displayed.

**Comment by cwlfw** [comment]
Hi Romain,

I just created a new page and here everthing works. It seems to be my 
layout-page is the reasen.

Many thanks for your help and best wishes!

Franz

Am 06.10.2016 um 14:07 schrieb Romain Canon:

**Comment by romm** [comment]
Hi @cwlfw,

Glad you solved it. I'm closing this topic.

Could you please send feedback when you finish testing the extension? I'd love to know what people think about it, and what improvements can be done.

You can find the contact page in the documentation: https://docs.typo3.org/typo3cms/extensions/formz/09-Contact/Index.html

Do not hesitate to join us on Slack: https://typo3.slack.com/messages/ext-formz/

**Comment by cwlfw** [comment]
Hi Romain,

for sure I try to work with formz and let you know in the next week.
In the meantime many thanks and best wishes.

Franz

Am 06.10.2016 um 14:50 schrieb Romain Canon:
