### ISSUE TITLE
File uploads get sanitized by javascript?

### ISSUE THREAD

**Issue by kftw** [romm/formz#64]
Hi! First of all, thank you for this amazing extension! I have one problem though: It seems that the formz javascripts removes `<input type="file">` fields on submit.

Additionally, multiple submit fields / buttons with unique names (for deciding what to do) don't work as well. Those come in handy if you want to upload a bunch of images before the actual form submit. 

Is there already a way to realize file uploads, disable (maybe parts of) javascript via typoscript or any workaround? 

Best regards
Klaus

**Comment by kftw** [comment]
Ok, it was a general javascript issue not related to formz. Sorry for bothering!

**Comment by romm** [comment]
Hi Klaus, I'm glad you could solve your issue by yourself. :)

Do not hesitate to join the [Slack channel](https://forger.typo3.org/slack) at [#ext-formz](https://typo3.slack.com/messages/C2J9L71D5/) where you can also ask basic questions.
