### ISSUE TITLE
Call to a member function setOption() on boolean 

### ISSUE THREAD

**Issue by haraldkrischner** [romm/formz#68]
Hi, 
I just found a regression in 1.1.1. 

I set custom options in my like this:
`<fz:option name="additional" value="FALSE" />` 
This works fine in 1.1.0, but fails with `Call to a member function setOption() on boolean` on the 1.1.1 release.
I haven't dug too deep yet into this release's code changes. Do I have to change my form structure?

Have a nice day

**Comment by romm** [comment]
Hi @haraldkrischner,

Thank you for the report.

After a quick lookup, I think the error comes from this line: https://github.com/romm/formz/blob/1.1.1/Classes/Service/ViewHelper/Field/FieldViewHelperService.php#L87 ; meaning the current field context can't be found in the method `getCurrentContext()`.

Where do you use the `<fz:option>` view helper? Is it inside a `<fz:field>`?

**Comment by haraldkrischner** [comment]
Nope, as I use a mixed order like this:
`<label for="a">a</label><label for="b">b</label><input id="a"><input id="b">`
I sometimes can not stay inside the field context… 
I know that my implementation looks kinda awkward but at least it worked ;)

**Comment by romm** [comment]
Hi @haraldkrischner,

Sorry for late answer, I wanted to take my time to consider the best answer to give!

Indeed your implementation is quite unusual, and will not be supported by default with FormZ.

The fact it did work before was an illusion, I just tried on local environment and with [these lines](https://github.com/romm/formz/blob/1.0.0/Classes/ViewHelpers/OptionViewHelper.php#L77-L79), an exception would always be thrown during the first loading of the page (when the template is not cached yet), then the error would disappear (!) and it would actually work (as you said). But that was actually a bug! You should never be authorized to use the `<fz:option>` view helper outside a field context.

I will provide a patch for a future version to prevent this.

---

Concerning your implementation, the best would, of course, be to change it to something more "common".

Still, you probably can achieve what you want, either by creating a custom layout (see [official documentation for layouts](https://docs.typo3.org/typo3cms/extensions/formz/06-IntegratorManual/Layouts.html)) or by writing HTML code directly in your template (see [HTML configuration documentation](https://docs.typo3.org/typo3cms/extensions/formz/06-IntegratorManual/Configuration.html#integratormanual-configuration)).

If you need help on this, don't hesitate to ask on Slack, I'd be glad to help you out. :)
