### ISSUE TITLE
manual

### ISSUE THREAD

**Issue by franzholz** [romm/formz#75]
The PDF file manual.formz-1.2.0.pdf has some misspellings:

    1  1.1.1
    The goal of FormZ is <<<

    1 2.2.2
    The boolean ... use several conditions <<<

    3.2
    to configure correctly your <<< validation rules

    4.1.2.1.5

    Function

    4.2.2
    list of available functions <<<

    5.1.3.8
    html contents which won't <<<

    >>> There are several wrong "wont" entries in the manual.

    5.1.5.3.2
    Works with <<<

**Comment by romm** [comment]
Thanks for the feedback, always a pleasure to see that people actually read the documentation. 😄
